\set ON_ERROR_STOP on
\connect episteme

ALTER TABLE EPISTEME.USER ADD CONSTRAINT FK_USER_CV_FILE FOREIGN KEY (CV_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.USER ADD CONSTRAINT FK_USER_PHOTO_FILE FOREIGN KEY (PHOTO_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.CONFERENCE ADD CONSTRAINT FK_CONFERENCE_METADATA_FILE FOREIGN KEY (METADATA_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.TRAINING ADD CONSTRAINT FK_TRAINING_METADATA_FILE FOREIGN KEY (METADATA_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.ANNOUNCEMENT ADD CONSTRAINT FK_ANNOUNCEMENT_METADATA_FILE FOREIGN KEY (METADATA_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.BLOG ADD CONSTRAINT FK_BLOG_METADATA_FILE FOREIGN KEY (METADATA_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.ACTIVITY ADD CONSTRAINT FK_ACTIVITY_METADATA_FILE FOREIGN KEY (METADATA_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.CONTENT_SUBMISSION ADD CONSTRAINT FK_CONTENT_SUBMISSION_CURRENT_VERSION FOREIGN KEY (CURRENT_CONTENT_SUBMISSION_VERSION_ID) REFERENCES EPISTEME.CONTENT_SUBMISSION_VERSION(ID) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS IDX_USER_ROLES_GIN ON EPISTEME.USER USING GIN (ROLES);

CREATE INDEX IF NOT EXISTS IDX_CS_OWNER ON EPISTEME.CONTENT_SUBMISSION (OWNER_USR_ID);
CREATE INDEX IF NOT EXISTS IDX_CS_CONFERENCE ON EPISTEME.CONTENT_SUBMISSION (CONFERENCE_ID);
CREATE INDEX IF NOT EXISTS IDX_CSV_CONTENT_SUBMISSION_ID ON EPISTEME.CONTENT_SUBMISSION_VERSION (CONTENT_SUBMISSION_ID);
CREATE INDEX IF NOT EXISTS IDX_CSM_SUBMISSION ON EPISTEME.CONTENT_SUBMISSION_MESSAGE (CONTENT_SUBMISSION_ID);

CREATE INDEX IF NOT EXISTS IDX_CRA_REVIEWER ON EPISTEME.CONTENT_REVIEW_ASSIGNMENT (REVIEWER_USR_ID);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICATION_USR ON EPISTEME.NOTIFICATION (USR_ID);

CREATE INDEX IF NOT EXISTS IDX_IDEMPOTENCY_KEY_EXPIRES_AT ON EPISTEME.IDEMPOTENCY_KEY (EXPIRES_AT);
