\set ON_ERROR_STOP on
\connect episteme

ALTER TABLE EPISTEME.USER ADD CONSTRAINT FK_USER_CV_FILE FOREIGN KEY (CV_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.USER ADD CONSTRAINT FK_USER_PHOTO_FILE FOREIGN KEY (PHOTO_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.CONFERENCE ADD CONSTRAINT FK_CONFERENCE_METADATA_FILE FOREIGN KEY (METADATA_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.TRAINING ADD CONSTRAINT FK_TRAINING_METADATA_FILE FOREIGN KEY (METADATA_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.ANNOUNCEMENT ADD CONSTRAINT FK_ANNOUNCEMENT_METADATA_FILE FOREIGN KEY (METADATA_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.BLOG ADD CONSTRAINT FK_BLOG_METADATA_FILE FOREIGN KEY (METADATA_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.ACTIVITY ADD CONSTRAINT FK_ACTIVITY_METADATA_FILE FOREIGN KEY (METADATA_FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE SET NULL;
ALTER TABLE EPISTEME.CONTENT_SUBMISSION ADD CONSTRAINT FK_CONTENT_SUBMISSION_CURRENT_VERSION FOREIGN KEY (CURRENT_CONTENT_SUBMISSION_VERSION_ID) REFERENCES EPISTEME.CONTENT_SUBMISSION_VERSION(ID) ON DELETE SET NULL;
