CREATE SCHEMA IF NOT EXISTS EPISTEME;

CREATE TABLE EPISTEME.USER (
  ID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMAIL           TEXT NOT NULL,
  FIRST_NAME      TEXT NOT NULL,
  LAST_NAME       TEXT NOT NULL,
  PHONE_NUMBER    TEXT NULL,
  PASSWORD_HASH   TEXT NOT NULL,
  ROLES           TEXT[] NOT NULL DEFAULT ARRAY['USER']::TEXT[],
  STATUS          INTEGER NOT NULL DEFAULT 0,
  STATUS_UPDATE_NOTES TEXT NULL,
  INSTITUTION     TEXT NOT NULL,
  OCCUPATION      TEXT NOT NULL,
  COUNTRY         TEXT NOT NULL,
  CV_FILE_ID      BIGINT NULL,
  PHOTO_FILE_ID   BIGINT NULL,
  LINKEDIN_URL    TEXT NULL,
  RESET_PASSWORD_TOKEN TEXT NULL,
  RESET_PASSWORD_EXPIRES_AT TIMESTAMP NULL,
  CREATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UQ_USER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE EPISTEME.CONFERENCE (
  ID                          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TITLE                       TEXT NOT NULL,
  SLUG                        TEXT NOT NULL,
  START_AT                    TIMESTAMP NOT NULL,
  END_AT                      TIMESTAMP NOT NULL,
  SUBMISSION_PERIOD_START_AT  TIMESTAMP NOT NULL,
  SUBMISSION_PERIOD_END_AT    TIMESTAMP NOT NULL,
  METADATA_FILE_ID            BIGINT NULL,
  STATUS                      INTEGER NOT NULL DEFAULT 0,
  CREATED_AT                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UQ_CONFERENCE_SLUG UNIQUE (SLUG)
);

CREATE TABLE EPISTEME.TRAINING (
  ID                          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TITLE                       TEXT NOT NULL,
  METADATA_FILE_ID            BIGINT NOT NULL,
  STATUS                      INTEGER NOT NULL DEFAULT 0,
  CREATED_AT                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EPISTEME.ANNOUNCEMENT (
  ID                          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TITLE                       TEXT NOT NULL,
  METADATA_FILE_ID            BIGINT NOT NULL,
  STATUS                      INTEGER NOT NULL DEFAULT 0,
  CREATED_AT                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EPISTEME.BLOG (
  ID                          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TITLE                       TEXT NOT NULL,
  METADATA_FILE_ID            BIGINT NOT NULL,
  STATUS                      INTEGER NOT NULL DEFAULT 0,
  CREATED_AT                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EPISTEME.ACTIVITY (
  ID                          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TITLE                       TEXT NOT NULL,
  METADATA_FILE_ID            BIGINT NULL,
  STATUS                      INTEGER NOT NULL DEFAULT 0,
  CREATED_AT                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EPISTEME.FILE (
  ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME         TEXT NOT NULL,
  STORAGE_KEY  TEXT NOT NULL,
  SIZE         BIGINT NOT NULL,
  SHA256       TEXT NULL,
  MIME_TYPE    TEXT NULL,
  UPLOADED_BY  BIGINT NOT NULL,
  CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UQ_FILE_STORAGE_KEY UNIQUE (STORAGE_KEY),
  CONSTRAINT CK_FILE_SIZE_NONNEG CHECK (SIZE >= 0),
  CONSTRAINT FK_FILE_UPLOADED_BY FOREIGN KEY (UPLOADED_BY) REFERENCES EPISTEME.USER(ID) ON DELETE RESTRICT
);

CREATE TABLE EPISTEME.CONTENT_SUBMISSION (
  ID                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  OWNER_USR_ID       BIGINT NOT NULL,
  TITLE              TEXT NOT NULL,
  TOPICS             TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  CONFERENCE_ID      BIGINT NOT NULL,
  DOI                TEXT NULL,
  CURRENT_CONTENT_SUBMISSION_VERSION_ID BIGINT NULL,
  CURRENT_STATUS     INTEGER NOT NULL DEFAULT 1,
  STATUS_UPDATE_NOTES TEXT NULL,
  CREATED_AT         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_CONTENT_SUBMISSION_OWNER FOREIGN KEY (OWNER_USR_ID) REFERENCES EPISTEME.USER(ID) ON DELETE RESTRICT,
  CONSTRAINT FK_CONTENT_SUBMISSION_CONFERENCE FOREIGN KEY (CONFERENCE_ID) REFERENCES EPISTEME.CONFERENCE(ID) ON DELETE CASCADE,
  CONSTRAINT CK_CONTENT_SUBMISSION_TOPICS_NO_NULLS CHECK (
    TOPICS IS NOT NULL AND NOT (TOPICS @> ARRAY[NULL]::TEXT[])
  )
);

CREATE TABLE EPISTEME.CONTENT_SUBMISSION_VERSION (
  ID                     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CONTENT_SUBMISSION_ID  BIGINT NOT NULL,
  UPLOADER_USR_ID        BIGINT NOT NULL,
  UPLOADER_USR_TYPE      TEXT NOT NULL,
  CHANGE_LOG             TEXT NULL,
  FILE_ID                BIGINT NOT NULL,
  CREATED_AT             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO             INTEGER NOT NULL,
  CONSTRAINT FK_CSV_SUBMISSION FOREIGN KEY (CONTENT_SUBMISSION_ID) REFERENCES EPISTEME.CONTENT_SUBMISSION(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CSV_UPLOADER FOREIGN KEY (UPLOADER_USR_ID) REFERENCES EPISTEME.USER(ID) ON DELETE RESTRICT,
  CONSTRAINT FK_CSV_FILE FOREIGN KEY (FILE_ID) REFERENCES EPISTEME.FILE(ID) ON DELETE CASCADE,
  CONSTRAINT CK_CSV_VERSION_NON_ZERO CHECK (VERSION_NO >= 1),
  CONSTRAINT UQ_CSV_SUBMISSION_VERSION UNIQUE (CONTENT_SUBMISSION_ID, VERSION_NO)
);

CREATE TABLE EPISTEME.CONTENT_SUBMISSION_MESSAGE (
  ID                            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CONTENT_SUBMISSION_ID         BIGINT NOT NULL,
  SENDER_USR_ID                 BIGINT NOT NULL,
  SENDER_USR_TYPE               TEXT NOT NULL,
  RECEIVER_USR_ID               BIGINT NULL,
  VISIBILITY_SCOPE              TEXT NOT NULL,
  MESSAGE                       TEXT NOT NULL,
  CREATED_AT                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_CSM_SUBMISSION FOREIGN KEY (CONTENT_SUBMISSION_ID) REFERENCES EPISTEME.CONTENT_SUBMISSION(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CSM_SENDER FOREIGN KEY (SENDER_USR_ID) REFERENCES EPISTEME.USER(ID) ON DELETE RESTRICT,
  CONSTRAINT FK_CSM_RECEIVER FOREIGN KEY (RECEIVER_USR_ID) REFERENCES EPISTEME.USER(ID) ON DELETE RESTRICT
);

CREATE TABLE EPISTEME.CONTENT_REVIEW_ASSIGNMENT (
  ID                      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CONTENT_SUBMISSION_ID   BIGINT NOT NULL,
  REVIEWER_USR_ID         BIGINT NOT NULL,
  ASSIGNED_BY_USR_ID      BIGINT NOT NULL,
  ASSIGNED_BY_NOTES       TEXT NULL,
  ASSIGNED_AT             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  STATUS                  INTEGER NOT NULL DEFAULT 1,
  STATUS_UPDATE_NOTES     TEXT NULL,
  CONSTRAINT FK_CRA_SUBMISSION FOREIGN KEY (CONTENT_SUBMISSION_ID) REFERENCES EPISTEME.CONTENT_SUBMISSION(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CRA_REVIEWER FOREIGN KEY (REVIEWER_USR_ID) REFERENCES EPISTEME.USER(ID) ON DELETE RESTRICT,
  CONSTRAINT FK_CRA_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY_USR_ID) REFERENCES EPISTEME.USER(ID) ON DELETE RESTRICT,
  CONSTRAINT UQ_CRA_SUBMISSION_REVIEWER UNIQUE (CONTENT_SUBMISSION_ID, REVIEWER_USR_ID)
);

CREATE TABLE EPISTEME.CONTENT_REVIEW (
  ID                                     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CONTENT_REVIEW_ASSIGNMENT_ID           BIGINT NOT NULL,
  CONTENT_SUBMISSION_VERSION_ID          BIGINT NOT NULL,
  REVIEWER_CONTENT_SUBMISSION_VERSION_ID BIGINT NULL,
  COMMENT                                TEXT   NULL,
  CREATED_AT                             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  RECOMMENDATION                         INTEGER NOT NULL,
  CONSTRAINT FK_CR_ASSIGNMENT FOREIGN KEY (CONTENT_REVIEW_ASSIGNMENT_ID) REFERENCES EPISTEME.CONTENT_REVIEW_ASSIGNMENT(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CR_VERSION FOREIGN KEY (CONTENT_SUBMISSION_VERSION_ID) REFERENCES EPISTEME.CONTENT_SUBMISSION_VERSION(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CR_REV_VERSION FOREIGN KEY (REVIEWER_CONTENT_SUBMISSION_VERSION_ID) REFERENCES EPISTEME.CONTENT_SUBMISSION_VERSION(ID) ON DELETE SET NULL,
  CONSTRAINT UQ_CR_ASSIGNMENT_VERSION UNIQUE (CONTENT_REVIEW_ASSIGNMENT_ID, CONTENT_SUBMISSION_VERSION_ID)
);

CREATE TABLE EPISTEME.CONTENT_SUBMISSION_PAYMENT (
  ID                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CONTENT_SUBMISSION_ID BIGINT NOT NULL,
  USR_ID              BIGINT NOT NULL,
  AMOUNT              NUMERIC(12,2) NOT NULL,
  CURRENCY            CHAR(3) NOT NULL,
  PROVIDER            TEXT NOT NULL,
  PROVIDER_PAYMENT_ID TEXT NOT NULL,
  STATUS              INTEGER NOT NULL DEFAULT 0,
  CREATED_AT          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_CSP_SUBMISSION FOREIGN KEY (CONTENT_SUBMISSION_ID) REFERENCES EPISTEME.CONTENT_SUBMISSION(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CSP_USER FOREIGN KEY (USR_ID) REFERENCES EPISTEME.USER(ID) ON DELETE RESTRICT,
  CONSTRAINT UQ_CSP_SUBMISSION UNIQUE (CONTENT_SUBMISSION_ID)
);
